version: '3.8'

services:
  frontend:
    build: 
      context: .
      target: runner
    ports:
      - "3000:3000"
    env_file: 
      - .env.local
    environment:
      - DOCKER_ENV=true  # Добавляем флаг Docker окружения
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:6
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - mongodb_data:/data/db
    env_file: 
      - .env.local  # Используем те же переменные
    ports:
      - "27017:27017"

volumes:
  mongodb_data: